/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MOJackal (https://sketchfab.com/MOJackal)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spacex-starship-spaceship-f5bbabadb7b44645a7fe9e0e619d555e
title: SpaceX Starship - Spaceship
*/

import React, { useRef } from 'react'
import { useGLTF/* , useAnimations */ } from '@react-three/drei'

export default function SpaceXShipScene(props) {
  const group = useRef()
  const { nodes/* , materials, animations */ } = useGLTF('/models/spaceXShipModel/scene.gltf')
  //const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[4,-15,0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={.8}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[1.09, 1.51, 0]}>
              <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} />
            </group>
            <group position={[1.09, 0.64, 0.11]} scale={[0.07, 0.06, 0.01]}>
              <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} />
            </group>
            <group position={[1.14, 0.64, 0.1]} rotation={[-Math.PI, 1.48, -Math.PI]} scale={[0.07, 0.06, 0.01]}>
              <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} />
            </group>
            <group position={[1.05, 9.27, 0]}>
              <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} />
            </group>
            <group position={[-1.09, 1.51, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} />
            </group>
            <group position={[-1.09, 0.64, 0.11]} rotation={[-Math.PI, 0, 0]} scale={[-0.07, -0.06, -0.01]}>
              <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} />
            </group>
            <group position={[-1.14, 0.64, 0.1]} rotation={[-Math.PI, 1.48, 0]} scale={[-0.07, -0.06, -0.01]}>
              <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} />
            </group>
            <group name="topleftwing_8" position={[-1.05, 9.27, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} />
            </group>
            <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
            <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
